name: Create Cluster

on:
  push:
    branches:
      - cluster


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
      - name: Check Cluster
        run: kubectl cluster-info --context kind-kind
      
