name: Minikube Cluster

on:
  pull_request:
    branches:
      - minikube


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Setup minikube 
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      - name: Setup Cluster
        run: minikube start
        
      - run: minikube kubectl get nodes  
      - run: minikube kubectl version
